server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://10.221.122.200:3306/house_property?useUnicode=true&characterEncoding=UTF-8
    username: root
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
upload:
  image:
    imagePath: /data/images/